[tools]
delta = "latest"
docker-cli = "latest"
docker-compose = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
harper-ls = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
lua-language-server = "latest"
markdownlint-cli2 = "latest"
node = "latest"
opencode = "latest"
# Needed for yamllint
pipx = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tree-sitter = "latest"
typos = "latest"
yamlfmt = "latest"
yamllint = "latest"
"github:coder3101/protols" = "latest"
"github:ilaborie/html2pdf" = "latest"
"go:github.com/daixiang0/gci" = "latest"
"go:github.com/reteps/dockerfmt" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:bash-language-server" = "latest"
"npm:pyright" = "latest"
"npm:tombi" = "latest"
"npm:yaml-language-server" = "latest"
