[tools]
codex = "latest"
docker-cli = "latest"
docker-compose = "latest"
fzf = "latest"
gemini-cli = "latest"
"github:coder3101/protols" = "latest"
"github:e-tho/bzmenu" = "latest"
go = "latest"
"go:github.com/reteps/dockerfmt" = "latest"
gradle = "latest"
harper-ls = "latest"
helm = "latest"
lazygit = "latest"
lua-language-server = "latest"
markdownlint-cli2 = "latest"
node = "latest"
"npm:bash-language-server" = "latest"
"npm:pyright" = "latest"
"npm:tombi" = "latest"
"npm:yaml-language-server" = "latest"
opencode = "latest"
pipx = "latest"
python = "latest"
stylua = "latest"
typos = "latest"
yamllint = "latest"
