keymap:
  - name: Copy Paste in terminal
    remap:
      Alt-v: Ctrl-Shift-v
      Alt-c: Ctrl-Shift-c
    application:
      only: Alacritty
  - name: Chrome
    remap:
      Alt-f: Ctrl-f
      Alt-l: Ctrl-l
      Alt-v: Ctrl-v
      Alt-c: Ctrl-c
      Alt-w: Ctrl-w
      Alt-r: Ctrl-r
      Alt-t: Ctrl-t
      Alt-Shift-t: Ctrl-Shift-t
      Alt-n: Ctrl-n
      Alt-Shift-n: Ctrl-Shift-n
    application:
      only: Google-chrome
