modmap:
  - name: Chrome
    remap:
      Alt_L: Ctrl_L
    application:
      only: Google-chrome

keymap:
  - name: Copy Paste in terminal
    remap:
      Alt-v: Ctrl-Shift-v
      Alt-c: Ctrl-Shift-c
    application:
      only: Alacritty
  - name: Chrome conflicting mappings
    remap:
      Ctrl-LeftBrace: Alt-Left
      Ctrl-RightBrace: Alt-Right
      Ctrl-Space: Alt-Space
      Ctrl-q: Ctrl-Alt-q
    application:
      only: Google-chrome
