gui:
  theme:
    selectedLineBgColor:
      - reverse
      - bold

git:
  paging:
    pager: delta --paging=never

customCommands:
  - key: P
    context: remoteBranches
    description: Push to specific remote branch
    prompts:
      - type: 'confirm'
        title: 'Push to {{ .SelectedRemoteBranch.RemoteName }}:{{ .SelectedRemoteBranch.Name }}'
        body: 'Are you sure you want to push to {{ .SelectedRemoteBranch.Name }} branch in {{ .SelectedRemoteBranch.RemoteName }} remote?'
      - key: PushCmd
        type: menu
        title: How to push?
        options:
          - value: push
          - value: push --force
    loadingText: Pushing...
    command: git {{ .Form.PushCmd }} {{ .SelectedRemoteBranch.RemoteName }} {{ .SelectedLocalBranch.Name }}:{{ .SelectedRemoteBranch.Name }}
    output: popup
