gui:
  theme:
    selectedLineBgColor:
      - reverse
      - bold

git:
  paging:
    pager: delta --paging=never

customCommands:
  - key: P
    context: remoteBranches
    description: Push to specific remote branch
    prompts:
      - type: 'confirm'
        title: 'Push to {{ .SelectedRemoteBranch.RemoteName }}:{{ .SelectedRemoteBranch.Name }}'
        body: 'Are you sure you want to push to {{ .SelectedRemoteBranch.Name }} branch in {{ .SelectedRemoteBranch.RemoteName }} remote?'
      - key: PushCmd
        type: menu
        title: How to push?
        options:
          - value: push
          - value: push --force
    loadingText: Pushing...
    command: git {{ .Form.PushCmd }} {{ .SelectedRemoteBranch.RemoteName }} {{ .SelectedLocalBranch.Name }}:{{ .SelectedRemoteBranch.Name }}
    output: popup

  - key: a
    context: stash
    description: "Apply stash"
    prompts:
      - type: 'confirm'
        title: 'Apply stash'
        body: 'Are you sure you want to apply stash?'
    command: git stash apply {{.SelectedStashEntry.Index}}
    output: popup

  - key: A
    context: stash
    description: "Apply reverse stash"
    prompts:
      - type: 'confirm'
        title: 'Apply reverse stash'
        body: 'Are you sure you want to apply reverse stash?'
    command: bash -c 'git stash show -p {{.SelectedStashEntry.Index}} | git apply --reverse'
    output: popup
