gui:
  theme:
    selectedLineBgColor:
      - reverse
      - bold

git:
  paging:
    pager: delta --paging=never

customCommands:
  - key: P
    context: remoteBranches
    description: Push to specific remote branch
    prompts:
      - type: 'confirm'
        title: 'Push to {{ .SelectedRemoteBranch.RemoteName }}:{{ .SelectedRemoteBranch.Name }}'
        body: 'Are you sure you want to push to {{ .SelectedRemoteBranch.Name }} branch in {{ .SelectedRemoteBranch.RemoteName }} remote?'
      - key: PushCmd
        type: menu
        title: How to push?
        options:
          - value: push
          - value: push --force
    loadingText: Pushing...
    command: git {{ .Form.PushCmd }} {{ .SelectedRemoteBranch.RemoteName }} {{ .SelectedLocalBranch.Name }}:{{ .SelectedRemoteBranch.Name }}
    output: popup

  - key: i
    context: files
    description: 'Ignore file from worktree'
    prompts:
      - type: 'confirm'
        title: 'Ignore file from worktree'
        body: '{{ if .SelectedFile }}Do you want to ignore {{ .SelectedFile.Name }} from worktree?{{ else }}Ignore file for worktree works only for files and not dirs{{ end }}'
    command: '{{ with .SelectedFile }}git update-index --skip-worktree {{ .Name }}{{ end }}'

  - key: I
    context: files
    description: 'Reconsider file for worktree'
    prompts:
      - type: 'menuFromCommand'
        title: 'Choose File to reconsider'
        key: 'FileToReconsider'
        command: bash -c "git ls-files -v | grep ^S || true"
        filter: S (?P<fileToReconsider>.*)
        valueFormat: '{{ .fileToReconsider }}'
    command: 'git update-index --no-skip-worktree {{ .Form.FileToReconsider }}'
