gui:
  theme:
    selectedLineBgColor:
      - reverse
      - bold

git:
  paging:
    pager: delta --paging=never

customCommands:
  - key: <c-p>
    context: global
    description: Push to different remote branch
    prompts:
      - key: Branch
        title: Remote branch
        type: menuFromCommand
        # Print remote branches except HEAD (HEAD is listed in output of git branch --remote).
        command: bash -c 'git branch  --remote --list {{.SelectedRemote.Name}}/* | grep -v HEAD'
        filter: '.*{{.SelectedRemote.Name }}/(?P<branch>.*)'
        valueFormat: '{{ .branch }}'
        labelFormat: '{{ .branch }}'
      - key: Cmd
        type: menu
        title: How to push?
        options:
          - value: push
          - value: push --force
    loadingText: Pushing...
    command: git {{.Form.Cmd}} {{.SelectedRemote.Name}} {{.SelectedLocalBranch.Name}}:{{.Form.Branch}}
    output: popup
