#! /bin/bash
echo "Make sure user nilesh is added"
cat << EOF >> /etc/pacman.conf

[archlinuxfr]
SigLevel = Never
Server = http://repo.archlinux.fr/$arch

EOF

# installing yaourt
pacman -Syu yaourt

su nilesh -c "yaourt xfwm4-git google-chrome visual-studio-code-bin xcursor-capitaine"