## enable or disable automatic sync
auto_sync = false

## enable or disable automatic update checks
update_check = false

## enable or disable showing a preview of the selected command
## useful when the command is longer than the terminal width and is cut off
show_preview = true
