#!/bin/bash

given_path=${1}
timestamp=`date +%Y%m%d`
dir=
if [[ "$given_path" == *\/* ]]; then
  dir=${given_path%/*}/
fi
file_name=${given_path##*/}
path_with_timestamp="${dir}${timestamp}-${file_name}"

hugo new $path_with_timestamp
