version: "2"
linters:
  default: all
  disable:
    - tagliatelle # Avoid linting for struct tag casing.
    - depguard    # Avoid limiting list of importable packages.
formatters:
  enable:
    - goimports
    - gci
    - gofumpt
  settings:
    # GCI config to sort imports in a specific order.
    gci:
      sections:
        - standard
        - default
        - localmodule
